### ISSUE TITLE
Could you write a MakeFile (or configure)?

### ISSUE THREAD

**Issue by FiveYellowMice** [WL-Amigo/waifu2x-converter-cpp#1]
I have no idea how to compile this, since I don't know cpp. I think there are many Linux user who don't know cpp either can't use this.

**Comment by alexey-lysiuk** [comment]
You can try this fork https://github.com/khws4v1/waifu2x-converter-cpp
It contains a shell script to build via CMake.

**Comment by FiveYellowMice** [comment]
Thank you! That works.
