### ISSUE TITLE
Thanks for your repository!

### ISSUE THREAD

**Issue by DaidoujiChen** [WL-Amigo/waifu2x-converter-cpp#6]
Hello @WL-Amigo,

I would like to re-implement waifu2x to Objective-C. May I use some of your code?

The other thing, it has very very bad performance on iOS, haha.
Maybe I will try to tune the performance more better. For the OTAKU world!
thank you.

**Comment by WL-Amigo** [comment]
Codes under src/ in this repository are licensed with MIT License, therefore you can use these codes in your any programs. For details, please see LICENSE.
And I appreciate that my codes are used in other program. Thank you!

But my re-implementation is too naive to run on mobile device (very slow and consume many battery power).
Reason of bad performance is that my implementation not uses GPU acceleration (for example, waifu2x-caffe uses GPU support and it has very good performance). 
So, I recommend using GPU on iOS device. This seems to be very difficult (at least for me), but this must become big contribution.

There is re-implementation of waifu2x's converting function with OpenGL Shading Language (GLSL).
This may also help you I think.
https://github.com/ueshita/waifu2x-converter-glsl

**Comment by DaidoujiChen** [comment]
Hello @WL-Amigo,

Thanks for your suggestion.
I will study more other repository for using native iOS device gpu.
